name: Sync Translation

on:
  workflow_dispatch:
  repository_dispatch:
    types: [FuChinese]

env:
    PARA_TOKEN: ${{ secrets.PARA_TOKEN }}
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
            python-version: "3.10"
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Setup Other Environment
        run: |
            pip install requests
            pip install pytz
            cd ${{github.workspace}}
            mkdir temp
            cd ${{github.workspace}}/script/tools
            chmod +x asset_packer
            chmod +x asset_unpacker
            cd ${{github.workspace}}
            cd temp
      - name: Download Translation
        run: |
            cd ${{github.workspace}}/script/tools
            python download_paratrans.py
      - name: Download Lastest FU
        id: downloadrelease      
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "sayterdarkwynd/FrackinUniverse"
          latest: true
          out-file-path: "temp"
          fileName: "FrackinUniverse.pak"
      - name: Extract Labels
        run: |
            cd ${{github.workspace}}/script/tools
            ${{github.workspace}}/script/tools/asset_unpacker ${{github.workspace}}/temp/FrackinUniverse.pak ${{github.workspace}}/temp/FrackinUniverse  
            python extract_labels.py
      - name: Sync to Paratranz
        run: |
            cd ${{github.workspace}}/script/tools
            python sync_to_paratrans.py
      - name: Make Mods
        run: |
            cd ${{github.workspace}}/temp
            mkdir paks
            cd ${{github.workspace}}/script/tools
            python export_mod_para.py
            ${{github.workspace}}/script/tools/asset_packer ${{github.workspace}}/translations/mods ${{github.workspace}}/temp/paks/FU_Schinese.pak
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: ${{github.workspace}}/temp/paks/FU_Schinese.pak
      - name: Upload Release
        uses: ncipollo/release-action@v1.13.0
        with:
            tag: ${{steps.downloadrelease.outputs.tag_name}}
            artifacts: "${{github.workspace}}/temp/paks/FU_Schinese.pak"
            allowUpdates: true
            token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Generate auth code
        id: generate
        uses: CyberAndrii/steam-totp@v1
        with:
            shared_secret: ${{ secrets.STEAM_TFASEED }}
      - name: Upload to Workshop
        run: steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} ${{ steps.generate.outputs.code }} +workshop_build_item ${{github.workspace}}/temp/mod.vdf +quit    
      - name: Delete Temp
        run: |
             cd ${{github.workspace}}
             rm -rf temp
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
            github_token: ${{ secrets.ACTIONS_TOKEN }}
            branch: Paratranz
      
        


            
