name: Sync Translation

on:
  workflow_dispatch:
  repository_dispatch:
    types: [FuChinese]

env:
  PARA_TOKEN: ${{ secrets.PARA_TOKEN }}

concurrency:
  group: fu-sync
  cancel-in-progress: false

jobs:
  workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: Paratranz

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Install dependencies
        run: |
          pip install -r ${{ github.workspace }}/script/tools/requirements.txt

      - name: Download Translation
        run: |
          python ${{ github.workspace }}/script/tools/run_ci.py download

      - name: Download Latest FU
        id: downloadrelease
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "sayterdarkwynd/FrackinUniverse"
          latest: true
          out-file-path: "temp"
          fileName: "FrackinUniverse.pak"

      - name: Extract Labels
        run: |
          chmod +x ${{ github.workspace }}/script/tools/asset_unpacker
          ${{ github.workspace }}/script/tools/asset_unpacker ${{ github.workspace }}/temp/FrackinUniverse.pak ${{ github.workspace }}/temp/FrackinUniverse
          python ${{ github.workspace }}/script/tools/run_ci.py process

      - name: Sync to Paratranz
        run: |
          python ${{ github.workspace }}/script/tools/run_ci.py sync

      - name: Make Mods
        run: |
          mkdir -p ${{ github.workspace }}/temp/paks
          python ${{ github.workspace }}/script/tools/run_ci.py export
          chmod +x ${{ github.workspace }}/script/tools/asset_packer
          ${{ github.workspace }}/script/tools/asset_packer ${{ github.workspace }}/translations/mods ${{ github.workspace }}/temp/paks/FU_Schinese.pak

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FU_Schinese.pak
          path: ${{ github.workspace }}/temp/paks/FU_Schinese.pak

      - name: Upload Release
        uses: ncipollo/release-action@v1.21.0
        with:
          tag: ${{ steps.downloadrelease.outputs.tag_name }}
          artifacts: "${{ github.workspace }}/temp/paks/FU_Schinese.pak"
          allowUpdates: true

      - name: Generate auth code
        id: generate
        uses: CyberAndrii/steam-totp@v1
        with:
          shared_secret: ${{ secrets.STEAM_TFASEED }}

      - name: Upload to Workshop
        run: |
          steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} ${{ steps.generate.outputs.code }} +workshop_build_item ${{ github.workspace }}/temp/mod.vdf +quit

      - name: Delete Temp
        run: |
          rm -rf ${{ github.workspace }}/temp

      - name: Commit & Push changes
        run: |
          cd ${{ github.workspace }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: sync translation memory [skip ci]" || echo "nothing to commit"
          git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git Paratranz
